### ISSUE TITLE
Plugin not installing from PyPI

### ISSUE THREAD

**Issue by jace** [untitaker/pytest-fixture-typecheck#2]
Given Python 3.9, pip 22.3.1 and pytest 7.2.0, install is not working as expected:

```
$ pip install pytest-fixture-typecheck
Collecting pytest-fixture-typecheck
  Using cached pytest_fixture_typecheck-0.1.0-py3-none-any.whl (1.9 kB)
Requirement already satisfied: pytest in […] (from pytest-fixture-typecheck) (7.2.0)
Requirement already satisfied: typeguard in […] (from pytest-fixture-typecheck) (2.13.3)
Requirement already satisfied: packaging in […] (from pytest->pytest-fixture-typecheck) (21.3)
Requirement already satisfied: iniconfig in […] (from pytest->pytest-fixture-typecheck) (1.1.1)
Requirement already satisfied: tomli>=1.0.0 in […] (from pytest->pytest-fixture-typecheck) (2.0.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in […] (from pytest->pytest-fixture-typecheck) (1.0.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in […] (from pytest->pytest-fixture-typecheck) (1.0.0)
Requirement already satisfied: attrs>=19.2.0 in […] (from pytest->pytest-fixture-typecheck) (22.1.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in […] (from packaging->pytest->pytest-fixture-typecheck) (3.0.9)
Installing collected packages: pytest-fixture-typecheck
Successfully installed pytest-fixture-typecheck-0.1.0
```

```
$ pytest --version
Traceback (most recent call last):
…
  File "[…]/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "[…]/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "[…]/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pytest_fixture_typecheck'
```

```
$ pip uninstall pytest-fixture-typecheck
Found existing installation: pytest-fixture-typecheck 0.1.0
Uninstalling pytest-fixture-typecheck-0.1.0:
  Would remove:
    […]/lib/python3.9/site-packages/pytest_fixture_typecheck-0.1.0.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled pytest-fixture-typecheck-0.1.0
```

It appears pip install creates a `dist-info` folder but does not install the source file.

**Comment by untitaker** [comment]
I just fixed the issue in 0.1.1, but please strongly consider vendoring this package's sourcecode in your conftest.py. The entire plugin is 5 lines of code.

**Comment by jace** [comment]
I've vendored it as a slightly different version:

```python
import typeguard
# Adapted from https://github.com/untitaker/pytest-fixture-typecheck
def pytest_runtest_call(item):
    for attr, type_ in item.obj.__annotations__.items():
        if attr in item.funcargs:
            typeguard.check_type(attr, item.funcargs[attr], type_)
```

Changes:

1. Using `pytest_runtest_call` shows it as a test failure instead of an internal error.
2. `item.obj.__annotations__` includes the return type annotation under the name `return`. My tests all have `-> None:` to turn on type checking and this code was failing with a KeyError in `item.funcargs[…]` so I've added a wrapper `if`.

**Comment by untitaker** [comment]
cool, feel free to create a pr!
